version: "2.1"
services:
  db:
    container_name: sample-db
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_DATATBASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin -uroot -proot ping
      interval: 20s
      timeout: 5s
      retries: 3
  wp:
    container_name: sample-wp
    build: .
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8080:80"
    links:
      - db:mysql
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: root